
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '1C96EFE1E2141CA407365DEC118DA84D'
    
_lr_action_items = {'HASH':([0,2,4,12,],[1,-4,7,-3,]),'NIL':([0,2,4,12,],[2,-4,8,-3,]),'FIGURE':([6,],[10,]),'COMPAS':([7,],[11,]),'TEMPO':([1,],[6,]),'NUMBER':([10,11,14,],[12,13,15,]),'DIV':([13,],[14,]),'$end':([3,5,8,9,15,],[-1,0,-6,-2,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'encabezado':([0,],[3,]),'tempo':([0,],[4,]),'exp':([0,],[5,]),'compas':([4,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> encabezado','exp',1,'p_exp','yacc.py',11),
  ('encabezado -> tempo compas','encabezado',2,'p_encabezado','yacc.py',16),
  ('tempo -> HASH TEMPO FIGURE NUMBER','tempo',4,'p_tempo','yacc.py',21),
  ('tempo -> NIL','tempo',1,'p_tempo_nil','yacc.py',26),
  ('compas -> HASH COMPAS NUMBER DIV NUMBER','compas',5,'p_compas','yacc.py',30),
  ('compas -> NIL','compas',1,'p_compas_nil','yacc.py',35),
]
