
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'A39979328218281F32D0ACC4B08DA663'
    
_lr_action_items = {'HASH':([0,3,8,],[1,6,-3,]),'FIGURE':([1,],[5,]),'COMPAS':([6,],[9,]),'NUMBER':([5,9,11,],[8,10,12,]),'DIV':([10,],[11,]),'$end':([2,4,7,12,],[-1,0,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'encabezado':([0,],[2,]),'tempo':([0,],[3,]),'exp':([0,],[4,]),'compas':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> encabezado','exp',1,'p_exp','yacc.py',11),
  ('encabezado -> tempo compas','encabezado',2,'p_encabezado','yacc.py',15),
  ('tempo -> HASH FIGURE NUMBER','tempo',3,'p_tempo','yacc.py',19),
  ('compas -> HASH COMPAS NUMBER DIV NUMBER','compas',5,'p_compas','yacc.py',23),
]
