
# /home/damian/Desktop/Damián/Computación/Tlen/TP2/tltp2/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '10EB17A12D3B6869F8B0FFD069D60403'
    
_lr_action_items = {'CONST':([2,10,40,43,50,],[6,-2,-15,6,-4,]),'NUMBER':([11,17,20,22,38,44,61,],[19,24,31,36,50,56,64,]),'DIV':([24,],[38,]),'VOICE':([2,7,10,16,40,43,47,50,55,],[-6,15,-2,15,-15,-6,-9,-4,-5,]),'DOT':([51,],[57,]),'LCURL':([9,13,48,49,62,],[18,21,-10,-11,66,]),'RPAREN':([36,37,51,52,56,57,70,71,],[48,49,-28,58,62,-29,74,75,]),'SEMICOLON':([31,58,74,75,],[43,63,78,79,]),'TEMPO':([1,],[5,]),'RCURL':([18,21,25,26,27,30,33,34,35,39,40,45,46,50,63,69,72,73,76,77,78,79,],[-19,-12,-19,40,-21,-22,-12,-12,47,-20,-15,-14,-13,-4,-30,-17,-17,77,-18,-16,-23,-24,]),'COMMA':([53,54,59,60,64,65,],[-26,61,-25,-27,67,68,]),'$end':([2,4,7,10,14,16,23,40,43,47,50,55,],[-6,0,-8,-2,-1,-8,-7,-15,-6,-9,-4,-5,]),'REPEAT':([21,33,34,40,50,77,],[32,32,32,-15,-4,-16,]),'HASH':([0,3,19,21,33,34,40,50,66,69,72,77,],[1,8,-3,8,8,8,-15,-4,8,8,8,-16,]),'FIGURE':([5,41,67,68,],[11,51,51,51,]),'NOTAID':([42,],[53,]),'EQUAL':([12,],[20,]),'LPAREN':([15,28,29,32,],[22,41,42,44,]),'CONSTID':([6,22,61,],[12,37,65,]),'COMPAS':([3,8,19,21,33,34,40,50,66,69,72,77,],[9,17,-3,9,9,9,-15,-4,9,9,9,-16,]),'NOTA':([18,25,27,30,63,78,79,],[29,29,-21,-22,-30,-23,-24,]),'SILENCIO':([18,25,27,30,63,78,79,],[28,28,-21,-22,-30,-23,-24,]),'ALTURA':([53,],[60,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'figura':([18,25,],[25,25,]),'bucle':([21,33,34,],[33,33,33,]),'notas':([18,25,],[26,39,]),'compas':([3,21,33,34,66,69,72,],[10,34,34,34,69,72,72,]),'encabezado':([0,],[2,]),'compases':([69,72,],[73,76,]),'notaProd':([18,25,],[27,27,]),'decla_instrumento':([7,16,],[13,13,]),'tempo':([0,],[3,]),'voces':([7,16,],[14,23,]),'simbolo_altura':([53,],[59,]),'start':([0,],[4,]),'musica':([21,33,34,],[35,45,46,]),'silencio':([18,25,],[30,30,]),'duracion':([41,67,68,],[52,70,71,]),'constantes':([2,43,],[7,55,]),'voz':([7,16,],[16,16,]),'altura':([42,],[54,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> encabezado constantes voces','start',3,'p_start','parser_rules.py',16),
  ('encabezado -> tempo compas','encabezado',2,'p_encabezado','parser_rules.py',21),
  ('tempo -> HASH TEMPO FIGURE NUMBER','tempo',4,'p_tempo','parser_rules.py',26),
  ('compas -> HASH COMPAS NUMBER DIV NUMBER','compas',5,'p_compas','parser_rules.py',32),
  ('constantes -> CONST CONSTID EQUAL NUMBER SEMICOLON constantes','constantes',6,'p_constantes','parser_rules.py',40),
  ('constantes -> <empty>','constantes',0,'p_constantes_lambda','parser_rules.py',45),
  ('voces -> voz voces','voces',2,'p_voces','parser_rules.py',49),
  ('voces -> <empty>','voces',0,'p_voces_lambda','parser_rules.py',53),
  ('voz -> decla_instrumento LCURL musica RCURL','voz',4,'p_voz','parser_rules.py',57),
  ('decla_instrumento -> VOICE LPAREN NUMBER RPAREN','decla_instrumento',4,'p_decla_instrumento','parser_rules.py',61),
  ('decla_instrumento -> VOICE LPAREN CONSTID RPAREN','decla_instrumento',4,'p_decla_instrumento_const','parser_rules.py',66),
  ('musica -> <empty>','musica',0,'p_musica_lambda','parser_rules.py',76),
  ('musica -> compas musica','musica',2,'p_musica_compas','parser_rules.py',80),
  ('musica -> bucle musica','musica',2,'p_musica_bucle','parser_rules.py',84),
  ('compas -> COMPAS LCURL notas RCURL','compas',4,'p_compas_def','parser_rules.py',88),
  ('bucle -> REPEAT LPAREN NUMBER RPAREN LCURL compas compases RCURL','bucle',8,'p_bucle','parser_rules.py',94),
  ('compases -> <empty>','compases',0,'p_compases_lambda','parser_rules.py',98),
  ('compases -> compas compases','compases',2,'p_compases','parser_rules.py',102),
  ('notas -> <empty>','notas',0,'p_notas_lambda','parser_rules.py',106),
  ('notas -> figura notas','notas',2,'p_notas','parser_rules.py',111),
  ('figura -> notaProd','figura',1,'p_figura_nota','parser_rules.py',116),
  ('figura -> silencio','figura',1,'p_figura_silencio','parser_rules.py',121),
  ('notaProd -> NOTA LPAREN altura COMMA NUMBER COMMA duracion RPAREN SEMICOLON','notaProd',9,'p_nota_prod','parser_rules.py',126),
  ('notaProd -> NOTA LPAREN altura COMMA CONSTID COMMA duracion RPAREN SEMICOLON','notaProd',9,'p_nota_prod_constid','parser_rules.py',132),
  ('altura -> NOTAID simbolo_altura','altura',2,'p_altura','parser_rules.py',141),
  ('simbolo_altura -> <empty>','simbolo_altura',0,'p_simbolo_altura_lambda','parser_rules.py',145),
  ('simbolo_altura -> ALTURA','simbolo_altura',1,'p_simbolo_altura','parser_rules.py',149),
  ('duracion -> FIGURE','duracion',1,'p_duracion','parser_rules.py',157),
  ('duracion -> FIGURE DOT','duracion',2,'p_duracion_punto','parser_rules.py',162),
  ('silencio -> SILENCIO LPAREN duracion RPAREN SEMICOLON','silencio',5,'p_silencio','parser_rules.py',167),
]
